[build]
command = "npm run build"
publish = "_site"
ignore = "git log -1 --pretty=%B | grep dependabot"

[dev]
command = "npm run start"
targetPort = 8_080
publish = "_site"
autoLaunch = false
framework = "#custom"

[[headers]]
for = "**/404.html"

  [headers.values]
  X-Robots-Tag = "noindex"

[[redirects]]
from = "/fr/*"
to = "/fr/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
