// WARNING! This file is generated by a tool.
// It exists only to allow PO editors to get translation keys from source code.
_("%s RSS feed")
_("menu")
_("Menu")
_("Inclusive Design Guide")
_("Insights")
_("Practices")
_("Techniques")
_("Activities")
_("The most recent posts from %s")
_("posts")
_("page")